version: '3.7'

services:
  service-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    container_name: EV-rds-test
    command:
      [
        "sh",
        "-c",
        "echo 'Test Container Up' && while true; do sleep 1000; done"
      ]
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASS=1234
      - POSTGRES_DB=postgres
    depends_on:
      - db

  service-keycloak:
    container_name: EV-keycloak
    image: quay.io/keycloak/keycloak:23.0.6
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KC_LOG_LEVEL=DEBUG
    command:
      - start-dev
      - --http-port=8180
      # - --import-realm
    ports:
      - "8180:8180"
    depends_on:
      - db

  db:
    container_name: "EV-psql"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
