version: "3.8"
services:
  # Minimal configuration for a PostgreSQL database
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${KM_DB_PASSWORD}
      POSTGRES_DB: ${KM_DB_NAME}
      POSTGRES_USER: ${KM_DB_USERNAME}

volumes:
  postgres:
