version: "3.8"
services:
  # Minimal configuration for a PostgreSQL database
  postgres:
    image: "postgres:alpine"
    container_name: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enterprise-wallet
      POSTGRES_USER: enterprise-wallet-user

volumes:
  postgres:
