# .github/workflows/frontend.yml
name: Frontend Deployment

on:
  push:
    paths:
      - "apps/frontend/**"
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  production:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--force --prod"
          vercel-org-id: "team_Men14SflVoRjJ10FRChV3qZ0"
          vercel-project-id: "prj_PiKWNnWByfmfMkjb52VwcLzeJgt5"

  preview:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel (Preview)
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--force"
          vercel-org-id: "team_Men14SflVoRjJ10FRChV3qZ0"
          vercel-project-id: "prj_PiKWNnWByfmfMkjb52VwcLzeJgt5"