name: Production

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  production:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v3

      - name: Vercel
        uses: amondnet/vercel-action@v25.1.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-args: "--prod" # Optional
          vercel-org-id: "team_Men14SflVoRjJ10FRChV3qZ0" # Required
          vercel-project-id: "prj_PiKWNnWByfmfMkjb52VwcLzeJgt5" # Required
